program ::=
			PROGRAM IDENT progParamList
			[GLOBAL cpsDecl] DO cpsCmd ENDPROGRAM;

decl ::= stoDecl
		| funDecl
		| procDecl;
stoDecl ::= [CHANGEMODE] typedIdent;
funDecl ::= FUN IDENT paramList
			RETURNS stoDecl
			[GLOBAL globImps]
			[LOCAL cpsStoDecl] DO cpsCmd ENDFUN;
procDecl ::= PROC IDENT paramList
		[GLOBAL globImps]
		[LOCAL cpsStoDecl] DO cpsCmd ENDPROC;
globImps ::= globImp {COMMA globImp};
globImp ::= [FLOWMODE] [CHANGEMODE] IDENT;
cpsDecl ::= decl {SEMICOLON decl};
cpsStoDecl ::= stoDecl {SEMICOLON stoDecl};

progParamList ::= LPAREN [progParam {COMMA progParam}] RPAREN;
progParam ::= [FLOWMODE] [CHANGEMODE] typedIdent;
paramList ::= LPAREN [param {COMMA param}] RPAREN;
param ::= [FLOWMODE] [MECHMODE] [CHANGEMODE] typedIdent;
typedIdent ::= IDENT COLON ATOMTYPE;

cmd ::= SKIP
	| BECOMES
	| IF THEN cpsCmd ELSE cpsCmd ENDIF
	| WHILE DO cpsCmd ENDWHILE
	| CALL IDENT [globInits]
	| DEBUGIN
	| DEBUGOUT;
cpsCmd ::= cmd {SEMICOLON cmd};
globInits ::= INIT idents;
idents ::= IDENT {COMMA IDENT};

expr ::= term1 {BOOLOPR term1};
term1 ::= term2 [RELOPR term2];
term2 ::= term3 {ADDOPR term3};
term3 ::= factor {MULTOPR factor};
factor ::= LITERAL
		| IDENT [INIT | exprList]
		| monadicOpr factor
		| LPAREN expr RPAREN;

monadicOpr ::= NOT | ADDOPR